# site properties and page defaults
title: Roberto Pili Lab
subtitle: University at Buffalo
description: Translation research in the field of genitourinary malignancies.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  PI Faculty  Page: https://medicine.buffalo.edu/faculty/profile.html?ubit=rpili
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: pili-lab-ub
  twitter: pili-lab-ub
  youtube: pili-lab-ub

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
